# Generated by Django 5.0.1 on 2025-11-21 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'md', 'txt'])])),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('md', 'Markdown'), ('txt', 'Text')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('chunk_count', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.JSONField(default=list, help_text='List of source documents and page numbers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('context_used', models.TextField(blank=True, help_text='Retrieved context used for answering')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
